Repository MSAClub/O-Homme-Micro-Server, pull requests merged in 2023-12, with the labels that each got.

#2 feat: add init discovery-server (#1)
  api-gateway/.gitignore
  api-gateway/Dockerfile
  api-gateway/build.gradle
  api-gateway/gradle/wrapper/gradle-wrapper.jar
  api-gateway/gradle/wrapper/gradle-wrapper.properties
  api-gateway/gradlew
  api-gateway/gradlew.bat
  api-gateway/settings.gradle
  api-gateway/src/main/java/com/example/apigateway/ApiGatewayApplication.java
  api-gateway/src/main/java/com/example/apigateway/config/test.java
  api-gateway/src/main/resources/application.yml
  api-gateway/src/test/java/com/example/apigateway/ApiGatewayApplicationTests.java
  demo/.idea/.gitignore
  demo/.idea/compiler.xml
  demo/.idea/gradle.xml
  demo/.idea/jarRepositories.xml
  demo/.idea/misc.xml
  demo/.idea/runConfigurations.xml
  demo/.idea/vcs.xml
  demo/Dockerfile
  demo/build.gradle
  demo/gradle/wrapper/gradle-wrapper.jar
  demo/gradle/wrapper/gradle-wrapper.properties
  demo/gradlew
  demo/gradlew.bat
  demo/src/main/resources/application.yml
Labels: init, 백엔드

#3 chore: update discovery-server name (#1)
  discovery-server/.idea/.gitignore
  discovery-server/.idea/compiler.xml
  discovery-server/.idea/gradle.xml
  discovery-server/.idea/jarRepositories.xml
  discovery-server/.idea/misc.xml
  discovery-server/.idea/runConfigurations.xml
  discovery-server/.idea/vcs.xml
  discovery-server/Dockerfile
  discovery-server/build.gradle
  discovery-server/gradle/wrapper/gradle-wrapper.jar
  discovery-server/gradle/wrapper/gradle-wrapper.properties
  discovery-server/gradlew
  discovery-server/gradlew.bat
  discovery-server/src/main/resources/application.yml
Labels: bug

#4 feat : add init product-service (#1)
  product/HELP.md
  product/build.gradle
  product/gradle/wrapper/gradle-wrapper.jar
  product/gradle/wrapper/gradle-wrapper.properties
  product/gradlew
  product/gradlew.bat
  product/settings.gradle
  product/src/main/java/com/msaclub/product/ProductApplication.java
  product/src/main/resources/application.yml
  product/src/test/java/com/msaclub/product/ProductApplicationTests.java
Labels: init, 백엔드, 기능

#5 feat : add init review-service (#1)
  review/.gitignore
  review/build.gradle
  review/gradle/wrapper/gradle-wrapper.jar
  review/gradle/wrapper/gradle-wrapper.properties
  review/gradlew
  review/gradlew.bat
  review/settings.gradle
  review/src/main/java/com/msaclub/review/ReviewApplication.java
  review/src/main/resources/application.yml
  review/src/test/java/com/msaclub/review/ReviewApplicationTests.java
Labels: 백엔드, 기능

#7 feat : add Dockerfile (#6)
  product/Dockerfile
  review/Dockerfile
Labels: init, 백엔드

#8 feat : add Dockerfile (#6)
  product/src/main/java/com/msaclub/product/ProductApplication.java
  review/src/main/java/com/msaclub/review/ReviewApplication.java
Labels: bug

#17 feat : add simple testController(#12)
  product/src/main/java/com/msaclub/product/controller/TestController.java
  product/src/main/resources/application.yml
Labels: :fire: 백엔드, :construction_worker: 기능, ✅ 테스트

#18 feat : add Test Properties(#12)
  product/build.gradle
  product/src/main/java/com/msaclub/product/ConfigUtil.java
  product/src/main/java/com/msaclub/product/ProductApplication.java
  product/src/main/java/com/msaclub/product/controller/TestController.java
  product/src/main/resources/application.yml
  product/src/main/resources/bootstrap.yml
Labels: 🌏 배포, :fire: 백엔드, :construction_worker: 기능, ✅ 테스트

#19 docs : edit application.yml (#12)
  api-gateway/src/main/resources/application.yml
  product/src/main/java/com/msaclub/product/controller/TestController.java
  product/src/main/resources/application.yml
Labels: :recycle: 리팩토링, :fire: 백엔드

#20 docs : edit application.yml (#12)
  api-gateway/src/main/resources/application.yml
Labels: :fire: 백엔드, :construction_worker: 기능

#25 feat: controller 및 .yml 수정 (#23)
  cart/src/main/java/com/msaclub/cart/controller/CartController.java
  cart/src/main/resources/application.yml
Labels: :rotating_light: 버그

#32 product Service MariaDB 연동 및 API 개발
  product/build.gradle
  product/src/main/java/com/msaclub/product/ConfigUtil.java
  product/src/main/java/com/msaclub/product/common/domain/BaseTimeEntity.java
  product/src/main/java/com/msaclub/product/common/uitl/ConfigUtil.java
  product/src/main/java/com/msaclub/product/controller/CategoryController.java
  product/src/main/java/com/msaclub/product/controller/ProductController.java
  product/src/main/java/com/msaclub/product/controller/TestController.java
  product/src/main/java/com/msaclub/product/domain/CategoryEntity.java
  product/src/main/java/com/msaclub/product/domain/ImageFileEntity.java
  product/src/main/java/com/msaclub/product/domain/ProductEntity.java
  product/src/main/java/com/msaclub/product/dto/CategoryDto.java
  product/src/main/java/com/msaclub/product/dto/ImageFileDto.java
  product/src/main/java/com/msaclub/product/dto/ProductReqeustDto.java
  product/src/main/java/com/msaclub/product/dto/StockRequestDto.java
  product/src/main/java/com/msaclub/product/repository/CategoryRepository.java
  product/src/main/java/com/msaclub/product/repository/ImageFileRepository.java
  product/src/main/java/com/msaclub/product/repository/ProductRepository.java
  product/src/main/java/com/msaclub/product/service/CategoryService.java
  product/src/main/java/com/msaclub/product/service/CategoryServiceImpl.java
  product/src/main/java/com/msaclub/product/service/ProductService.java
  product/src/main/java/com/msaclub/product/service/ProductServiceImpl.java
  product/src/main/resources/application.yml
  product/src/main/resources/bootstrap.yml
Labels: 🌏 배포, :fire: 백엔드, :construction_worker: 기능, 📬 API
